//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorselfinali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demirbas
    {
        public int DemirbasID { get; set; }
        public string DemirbasAdi { get; set; }
        public string DemirbasTuru { get; set; }
        public string DemirbasBilgisi { get; set; }
        public Nullable<bool> DemirbasAktifmi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
    }
}
