//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorselfinali
{
    using System;
    using System.Collections.Generic;
    
    public partial class Derslik
    {
        public int DerslikID { get; set; }
        public string DerslikAdi { get; set; }
        public string DerslikBinasi { get; set; }

        internal void Show()
        {
            throw new NotImplementedException();
        }
    }
}
