//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorselfinali
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gorselfinalEntities : DbContext
    {
        public gorselfinalEntities()
            : base("name=gorselfinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<ayniyat> ayniyat { get; set; }
        public virtual DbSet<Bina> Bina { get; set; }
        public virtual DbSet<Demirbas> Demirbas { get; set; }
        public virtual DbSet<PersonelBirim> PersonelBirim { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vBirimler> vBirimler { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<vKullanici> vKullanici { get; set; }
        public virtual DbSet<Zimmet> Zimmet { get; set; }
        public virtual DbSet<vPersonel> vPersonel { get; set; }
        public virtual DbSet<vZimmetler> vZimmetler { get; set; }
        public virtual DbSet<Derslik> Derslik { get; set; }
    }
}
