//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorselfinali
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKullanici
    {
        public int PersonelID { get; set; }
        public string PersonelTCNO { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public Nullable<int> PersonelRolID { get; set; }
        public string BirimAdi { get; set; }
        public string BirimKodu { get; set; }
        public string Personelka { get; set; }
        public string Personelsifre { get; set; }
        public string Gorev { get; set; }
    }
}
